### ISSUE TITLE
not compatible with internet explorer

### ISSUE THREAD

**Issue by akramwahid** [shentao/vue-multiselect#1095]
This plugin doesn't work in internet explorer when I try to use it via CDN, problem must be with plugin it self, because when I download the source code from your git branch to local and run in internet explorer, it is not working, 

although your demo works when I run it directly in ie browser from your documentation URL, so demo on your server must be using the NPM and not CDN if i am correct????

![Untitled](https://user-images.githubusercontent.com/1542863/65542221-6ef06180-df17-11e9-80c8-29c788aa8aea.png)
have a look in the attached screenshot, it works in firefox  but not in ie in local

**Comment by shentao** [comment]
What is the error thrown by IE?

**Comment by akramwahid** [comment]
After long try, I found the issue, when I use template for options, it it doesn't work in ie, also doesn't raise any error in console, 
` <multiselect v-model="itemEdit.position" open-direction="bottom" :options="position_options" placeholder="Select a Position" :taggable="true" tag-placeholder="Add this as a new Position" @tag="addNewPositionOnUpdate">
                                              <template slot="singleLabel" slot-scope="{ option }"> <strong>@{{ option }}</strong> <i class="fa fa-check text-success"></i></template>
                                            </multiselect>` 

but when i use it without template slots, it works perfect, 
` <multiselect v-model="itemEdit.position" open-direction="bottom" :options="position_options" placeholder="Select a Position" :taggable="true" tag-placeholder="Add this as a new Position" @tag="addNewPositionOnUpdate">                                          
                                            </multiselect>`

**Comment by nuller1joe** [comment]
If anybody ends up here the fix for this in Internet Explorer is to replace 
`slot-scope="{ option, search, remove, }"` with `slot-scope="funcs"`. Option, search and remove are now stored in an object called funcs. The three objects/functions can be acceses by  `funcs.option`, `funcs.search` and `funcs.remove.`

as such, to answer @akramwahid  original question, this is fixed by:

`<multiselect v-model="itemEdit.position" open-direction="bottom" :options="position_options" placeholder="Select a Position" :taggable="true" tag-placeholder="Add this as a new Position" @tag="addNewPositionOnUpdate"> <template slot="singleLabel" slot-scope="funcs"> <strong>@{{ funcs.option }}</strong> <i class="fa fa-check text-success"></i></template> </multiselect>`
