### ISSUE TITLE
issue in setting value in v-model that not having a value in options

### ISSUE THREAD

**Issue by santhoshbalusamy** [shentao/vue-multiselect#1226]
### Reproduction Link

https://jsfiddle.net/r0kwobz2/9/
or 
https://jsfiddle.net/8zakrgf3/

### Steps to reproduce
Set the value in v-model that is not available in options and it is populated in the selected value in the dropdown 

### Expected behaviour

If we set the value in v-model that is not available in options, it won't populate in the dropdown

### Actual behaviour

value in v-model that is not available in options, it is populated in the dropdown.

<img width="1230" alt="Screenshot 2020-04-02 at 3 44 41 PM" src="https://user-images.githubusercontent.com/23396872/78238018-b32d7180-74f9-11ea-8efc-df81d3e3764e.png">

**Comment by santhoshbalusamy** [comment]
@shentao Can you please look into this?

**Comment by shentao** [comment]
Hey! This is the desired behaviour. It enables asynchronous selects where the options list is changing dynamically without affecting the already selected elements. Since you can use `@input + :value` instead of `v-model` I would recommend running that check yourself in the `@input` handler. If the value is being populated somewhere else with invalid data, it’s not a concern of the component.
