### ISSUE TITLE
Feature request: Event after tags have been rendered

### ISSUE THREAD

**Issue by kontur** [shentao/vue-multiselect#1255]
Hey,

thanks for the amazing component. I'm using this on my first Vue project and it was one of the first premade components I started using and it was very easy to get set up and configuring.

I have a case where I want to alter the display based on when the tags box overflows a certain height. Right now I am doing this with the `select` event and a clumsy timeout that executes a few milliseconds after (when I can assume the tags have rendered and do or do not overflow my limit) — it would be great to have a "tags rendered" event to hook into for this.

Or is there another way to do this in Vue... like can I hook into the components render cycle somehow to do my calculation on `updated` or something similar?

**Comment by Zyberg** [comment]
First of all, check this handy function out: `$nextTick(function () {...})`. It will run it's callback after the DOM is rendered. That might be all you need! Otherwise, I present you a few thoughts below: 

You could try to use a watched property for your selected items value:
```
...
data () {
    return {
        isOverflowing: false,
    }
},
watch: {
    value (valueNew) {
          if (calculateTheHeightOrWhateverWithThisFunction(valueNew)) this.overflowing = true
    }
}
```

The height calculation function implementation depends on what you really want. If you know that your multiselect input will always be constant width, then just check what is the max number of characters that fit in a row, then count how much space every tag with their margins use up and you are good to go.
However, this sounds like a hassle, in my opinion. What you could do is simply add the new selected item with `visibility: hidden`, calculate height, set conditional rendering. Sounds a little simpler, even if in the most extreme scenarios a little slower.

**Comment by kontur** [comment]
Cheers for the `$nextTick` pointer and showing how to work around this the Vue Way™ :)
I suppose this is the kind of edge case that is rarely needed, so I'll close the issue.
