### ISSUE TITLE
Remove tag close button not working, keeps on adding after select second element, if first element when trying to remove

### ISSUE THREAD

**Issue by milanamatya** [shentao/vue-multiselect#1266]
- In multiselect mode, add first item, when trying to remove it does not work

- and add second item, when trying to remove second element, it adds first element and keeps on adding it.

**Comment by leeniu** [comment]
Hey @milanamatya, Could you please provide an example? Here is a JSFiddle you can work with: https://jsfiddle.net/leeniu/o72f1vwz/

**Comment by milanamatya** [comment]
I have created the issue here. https://jsfiddle.net/9to8ky4j/ 
Please follow the previous comment @leeniu

**Comment by LensHunnel** [comment]
I've encountered the same issue, it wasn't on the version 2.0.8

**Comment by shentao** [comment]
Hey! Yeah, this issue comes from the fact that the component has no way of identifying the components due to the lack of `track-by`.
Please see: https://vue-multiselect.js.org/#sub-single-select-object

`track-by` is required for all vue-multiselect instances that handle options that are objects.
@leeniu We might want to phrase it differently in the new docs to avoid such confusion in the future.
