### ISSUE TITLE
"Searchable" property removes ability to click SingleLabel

### ISSUE THREAD

**Issue by karmado** [shentao/vue-multiselect#1269]
I'm trying to use clickable labels, that open a link to a selected resource. This works fine with multiple selections. With single selections (:multiple="false") it does not work, if "searchable" is set to "true".

This might have something to do with the SingleLabel HTML element being completely removed when the searchbar opens.

### Reproduction Link
https://jsfiddle.net/9hyaqnjc/1/
(tested in FireFox 76.0.1)

### Steps to reproduce
- open the reproduction link
- select something
- click the selected SingleLabel
--> nothing happens

- in the fiddle set :searchable="false" and repeat the steps above
--> the counter "clicks on label" increments

### Expected behaviour
When "searchable" is activated for single selections, the label should still be clickable.

### Actual behaviour
The label is not clickable.

**Comment by Zyberg** [comment]
With single selection, you could replicate your functionality without using the slot!
Use `@select` event to trigger the navigation.

**Comment by LedzZm** [comment]
Hey there. 
I am not a maintainer in this project and i am not 100% confident that i am right, but i believe there is no bug here, and what you are trying to do is something that is not an intended behaviour.

Having said that... If i understand your case correctly, you want to be able to click on the selected option which will probably be a link to something. If i am right then in the fiddle below you will see a workaround i created to produce that.
https://jsfiddle.net/xa8cg6nm/1/

There are two things i did differently. First of all you are trying to call the removeElement of the multiselect mixin but this is not possible since the method is not available in your nested template.
To work around this, I added a ref to the "parent" multiselect component, to be able to use its methods in your nested template like so: $refs.multiselect.removeElement(option)
I am confident that this is messy code and that there is a better way, but i am not so hot on Vue yet sry :P.

Now on to the problem at hand. Reading the code of the multiselect component i see that if the singleLable is set to true, they use the toggle function (opens and closes the options) on the mousedown event, while using preventDefault and stopPropagation (mousedown.prevent.stop), and by doing that they cancel all mousedown events on the component and all its parents. So i did the same, but without calling any function. This way the link in the label is normally clickable.
This is also a messy workaround, but i will let the project's maintainers give more clarifications considering that.

I hope I helped you patch your problem (even if not in the most elegant way).

Best Regards.

**Comment by karmado** [comment]
Many thanks, the `@mousedown.prevent.stop` does the trick. And the other problem I hadn't even realized without your help. 

Still I'm a bit confused, why the "singleLabel"-slot handles different to the "tag"-slot. There is no problem using the `@click` for the `:multiple="true"` select (with or without `:searchable="true"`). I'm not even sure why there have to be different slots for single and multiple labels.

Unless a maintainer wants to leave a comment here to clarify it a bit, I will close the issue by the end of the week, since the workaround is fine by me.

**Comment by LedzZm** [comment]
I believe that the tags themselves are not meant to be clickable and if you think about it it makes sense. The aim of a select widget is to allow you to chose 1 or more options out of an array of more options (:P) and do something with them.
No concerning your case, i believe that printing the urls as hyperlinks in a different area in your html would make more sense (As is shown in this fiddle https://jsfiddle.net/xsy039kg/)

I would also remove the tags styling as you see, since it does not really make to have a remove button for singleLabel... just choose another :P

Then again I will let a maintainer clarify, because i might as well be wrong.

**Comment by karmado** [comment]
If you remove the "remove button" for a single label, you can't easily deselect an item, if an empty selection is allowed. You would have to go through all options and click the one that is already selected. 

Also I think there is definately a use case for selects with clickable options. The Vue-Multiselect supports tagging. So let's say you have a book database where users could tag their books with words like "romance", "sci-fi/fantasy" or "set in Australia" on the fly - of course you want to click the tags to find more books "set in Australia". It would look quite odd to list every selected tag in a select and then list it again, only to make it clickable.
Sure, in most cases it is a good idea to seperate the view from the input, but it is not always desired.

**Comment by Zyberg** [comment]
> If you remove the "remove button" for a single label, you can't easily deselect an item, if an empty selection is allowed. You would have to go through all options and click the one that is already selected.
> 
> Also I think there is definately a use case for selects with clickable options. The Vue-Multiselect supports tagging. So let's say you have a book database where users could tag their books with words like "romance", "sci-fi/fantasy" or "set in Australia" on the fly - of course you want to click the tags to find more books "set in Australia". It would look quite odd to list every selected tag in a select and then list it again, only to make it clickable.
> Sure, in most cases it is a good idea to seperate the view from the input, but it is not always desired.

Why wouldn't you want to separate the input form for tags from the view screen tho? While I believe clickable tags could be a use case, you example seems to be a little bad in UX sense:
User goes to that website with a phone. They have big thumbs or whatever, they try to click on a tag to deselect it, but! - redirect to similar books. Not too friendly + a mesh of concerns in one place

**Comment by karmado** [comment]
You are right, that the example wasn't the best one. It is also not what I am working on.

Although it does not seem to be a problem at the moment or any time soon, I'll keep the fiddliness for mobile users in mind. Thanks for pointing that out!

**Comment by karmado** [comment]
Since there are no additional comments and the originial issue is somewhat fixed for me with the workaround, I'll close this one. 

Thanks for your help!
