### ISSUE TITLE
Vue 3 @input event not working

### ISSUE THREAD

**Issue by rrpatricio** [shentao/vue-multiselect#1452]
I couldn't use the @input event because it seems it is not firing when the v-model changes on Vue 3 implementation.

**Comment by mattelen** [comment]
Hi @rrpatricio. This is because on Vue 3, the v-model directive now uses `modelValue` as the prop and `@update:model-value` as the update event. So instead of using `@input` you would use  `@update:model-value`. Check out the examples in the readme for more information: https://github.com/shentao/vue-multiselect/tree/next.
Hope that helps. Let me know if something is unclear

**Comment by OZcomingFRoo** [comment]
> Hi @rrpatricio. This is because on Vue 3, the v-model directive now uses `modelValue` as the prop and `@update:model-value` as the update event. So instead of using `@input` you would use `@update:model-value`. Check out the examples in the readme for more information: https://github.com/shentao/vue-multiselect/tree/next. Hope that helps. Let me know if something is unclear

I am not sure if [this](https://vue-multiselect.js.org/) their official website, but it's really not updated.
The event `@update:model-value` works as you said and the `@input` event is not working at all.

It's really weird from them to not UPDATE their guide on this critical change.
It made me lose my mind for an hour just found your answer
