### ISSUE TITLE
[3.0 change] please have :multiple="true" by default

### ISSUE THREAD

**Issue by mariusa** [shentao/vue-multiselect#1471]
This vue-multiselect component is mostly used for multiple values selection.

Taking advantage of 3.0 release, would you please consider having ` :multiple="true"` by default?
For single select, one would need to set  `:multiple="false"`

Thanks!

**Comment by mattelen** [comment]
Thanks for adding this suggestion @mariusa. From what I can see from reactions of your post (5x thumbs down), uses around the internet, and from how I use the component, I think we would want to keep multiple as false by default. I know that I mostly use it as `:multiple="false"`. 
While it might seem a bit weird being the name of the component is multiselect, I use this component for both single and multi-select situations because both situations have so much cross over in terms of code, features and design, that I do just use the one component for both. 

I'm going to close this issue, but if there are enough voices on this who are keen to have this change, it can be re-reviewed
Thanks

**Comment by mariusa** [comment]
Your reasoning makes sense. Thanks for considering!
