### ISSUE TITLE
Prevent tags from appearing with multiple select

### ISSUE THREAD

**Issue by chrissyast** [shentao/vue-multiselect#1519]
### Reproduction Link
https://codesandbox.io/s/determined-hill-sf6by?file=/src/App.vue

### Steps to reproduce
Make a selection

### Expected behaviour
Tags do not appear in the search bar, content below select does not move

### Actual behaviour
Tags appear and expand the select box, causing content below to move. 

### Additional info
Expected behaviour is achieved with a near identical setup in the example on https://vue-multiselect.js.org/#sub-multiple-select but this doesn't happen for me.

Expected behaviour can be achieved by adding an empty tag slot `<template slot="tag"><div></div></template>` but from the above example it doesn't seem like it should be necessary

**Comment by lehoaibaokg** [comment]
Based on the documentation, I think tag slot is the best solution

**Comment by mattelen** [comment]
Hi @chrissyast. Thanks for creating a reproducible link and explaining this, however I'm struggling to see what the issue is. In your sandbox, after I've selected some tags, and after I've collapsed the list, it currently hides the tags as it does in the example in the docs - so I'm not seeing any difference here

![image](https://user-images.githubusercontent.com/9289772/185651470-881d4a06-d840-4898-9b23-611c73b96629.png)

Was that the issue, or is it something else?
