### ISSUE TITLE
Tabindex is mutually exclusive with searchable

### ISSUE THREAD

**Issue by devcrazygit** [shentao/vue-multiselect#1540]
### Expected behaviour
I've set `tabindex` props as 0, and I want let it works.
But it remains -1 after building

I've found the reason.

https://github.com/shentao/vue-multiselect/blob/8b82146a24a8c5c201db5c9bf65f7bd9f94a9852/src/Multiselect.vue#L3

I can't understand why you made `searchable` and `tabindex` exclusive.
If it is not necessary, can I make a pull request?

**Comment by mattelen** [comment]
Hi @devcrazygit 

This is setup like this so when the component is searchable, the input that the user will type into gets the tabindex, as you can see here:
https://github.com/shentao/vue-multiselect/blob/685f245933df2625e36b9ef404b7cd5d28d378e4/src/Multiselect.vue#L59

So that is the reason why we have that. Hope that helps, thanks for creating an issue and asking
