### ISSUE TITLE
Error: blur() invoked on null object.

### ISSUE THREAD

**Issue by malarium** [shentao/vue-multiselect#1716]
### Steps to reproduce
Click on Multiselect and while focused click back button on the browser (go back -1 in history).

### Expected behaviour
No error.

### Actual behaviour
Error: trying to perform blur() on null object.

**Comment by nerminjukan** [comment]
Hi,

we also have a similar error related to blur: "Cannot read properties of null (reading 'blur')", it is triggered when search input is populated and the "searched" option is selected. The tag is properly set, however the error is triggered.

We believe it is related to an issue, that was once already resolved, but we checked the code and this piece of code was since updated and the issue is back: https://github.com/shentao/vue-multiselect/issues/1421

We are using version: 3.0.0-beta.2
Vue: 10.2.1

**Comment by mattelen** [comment]
Fixed pending new version release

**Comment by giladna** [comment]
@mattelen what is the next release date with this fix?
could you tag this version so we can use it please?
