### ISSUE TITLE
dark mode - style group nodes

### ISSUE THREAD

**Issue by choper725** [shentao/vue-multiselect#1800]
any help on how to style the group tags in dark mode ?

**Comment by mattelen** [comment]
Have a play around with the CSS file, and make your own customisation: https://github.com/shentao/vue-multiselect/blob/master/dist/vue-multiselect.css

The CSS needs to be inserted separately into your app, so instead of referencing the CSS that is part of the library, you can reference your own file

Alternatively, feel free to start a discussion about it
