### ISSUE TITLE
:bug Done keyboard iOS event

### ISSUE THREAD

**Issue by nikolaynesov** [shentao/vue-multiselect#332]
Done keyboard iOS event is not handled correctly. 
Expected: when the option is selected and Done is pressed, the option should be added.
Now: Pressing Done always closes the select box and clears the input.

![fullsizerender 7](https://cloud.githubusercontent.com/assets/17743574/24407166/e6d23542-13d2-11e7-85a5-decad2e5c6ea.jpg)

**Comment by shentao** [comment]
Thanks for pointing this out! Seems like the *Done* button should be handled just like the *return* event. Will have to play with it why is it not working right now.

**Comment by shentao** [comment]
Seems there’s no way target the *done* button from JavaScript. :/

**Comment by lionel-bijaoui** [comment]
Hello, maybe there is a solution with this
https://stackoverflow.com/questions/4971061/capture-done-button-click-in-iphones-virtual-keyboard-with-javascript
> The done key is the same as the enter key

The idea would be to listen to `keypress` on focus (maybe ?) and check the `keyCode` or `key` value that is equal to the key "enter".
This bug is really disturbing to the user, as he might expect "Done" or "Ok" (in French) to validate the value.
I hope this issue can reopen.

**Comment by shentao** [comment]
I remember I’ve been experimenting with this a while ago. If I remember correctly all it did was to blur the input, which is the same as if one would just click outside of the drop-down. 
Would you like to provide an example of the `done` button being handled properly?

**Comment by lionel-bijaoui** [comment]
I don't have an iPhone so I can't really help, sorry 😞
