### ISSUE TITLE
custom click action in noResult-slot not working

### ISSUE THREAD

**Issue by mgmeiner** [shentao/vue-multiselect#355]
I want to have a custom button with a custom click event in the noResult slot but all the click events in this slot are not beeing fired. 

Fiddle for reproduction: https://jsfiddle.net/7csp2vtp/

Is there already a solution for this problem?

Any help would be great.

**Comment by shentao** [comment]
It might be related to the `onmousedown` event. Hopefully I will look into it during the weekend.

**Comment by parth115** [comment]
+1 having same issue
Trying to trigger a link from inside span

**Comment by fderoo** [comment]
Just for others to know, this issue seems to be solved as of the last commit.

The demo site exemple ( https://monterail.github.io/vue-multiselect/ ) is not up to date, and neither is NPM but it will as soon as @shentao updates it.

If you cannot wait, build it from the 2.0 branch (git clone, npm update, then npm run bundle) will generate the dist file that you can use. Not the best practice as it will be erased after a npm update, but it works.

**Comment by nafiulislamtony** [comment]
Is NPM update done? I'm facing the same issue in 2.0.2 build

**Comment by Oscarato** [comment]
this is not resolved

**Comment by Oscarato** [comment]
I found a solution on this version: add click event on slot "noResult" and add styles with CSS to cover the entire element.

Example:

<span class="**add**" slot="noResult" @click="CustonFunction">Agregar </span>
<stylus>
   .add
         margin: -0.6rem -1rem
         padding: 0.6rem 1rem
         width: calc(100% + 2rem)
         display: block

**Comment by shentao** [comment]
This issue is no longer present.
