### ISSUE TITLE
[Feature Request] Validation or Promise style reject/accept

### ISSUE THREAD

**Issue by OwenMelbz** [shentao/vue-multiselect#410]
Hey, recently we found ourself in a situation where we had a collection of data similar to 

```js
const products = [
    {id: 1, label: 'item 1'},
    {id: 2, label: 'item 2'}
];
```

When an item is picked, the "selected" event occurs.

We then had to do something like 

```js
   axios.get(`/stock-check/${item.id}`)
   .then(response => {
        if (response.data.stock_count == 0) {
             pickedProducts = _.reject(pickedProducts, {id: item.id});
        }
    });
```

So effectively using the callback, (the item got added), then if for some reason it shouldn't be added, we had to remove it again.

After a chat on Twitter it became apparent there could be 2 ways to approach this.

1. Document within the website how you can "bypass" the model binding, to run your own code, before pushing it to the model collection.

2. Create a validation property which could run a method to return if the item should be added or not, most likely a Promise style so a series of other things could happen before the chain is considered resolved.

Hopefully this makes sense? If you need me to explain a little more than I'll be more than happy to!

Thanks :D

**Comment by shentao** [comment]
Hey! Thanks for submitting the feature request.

When it comes to validation (2nd option) – supporting promises might be very hard as it would mean that the multiselect would become unresponsive for some time. That means also the need to implement the 1st approach. Otherwise, it would become a very similar flow that you have currently (select stuff, then remove).

I might play around just implementing the 1st approach to see if doesn’t cause too many breaking changes – no promises here.

What I would suggest here is to not use multiselect for this problem or only a part of it. For example, just use it as a search box for products, but after someone picks something (`@input="reset"`).

```
reset () { this.value = [] }
```

This should clear the multiselect but let you use whatever the user selected through `@select`. After that, you could add the selected product above/below the searchbox with a nice spinner next to it that states that the app is checking it’s availability. Multiselect itself is probably not the best place to handle such validations.

A very raw idea: https://jsfiddle.net/p1Lk2aex/

**Comment by OwenMelbz** [comment]
I had thought about the "busy" state, we've got a method we call which adds a loading screen.

The example I gave was very simplified and not actually what we're doing :D and when designs have already been approved for the build is fairly tricky to change the user journey/layout.

I've uploaded a quick demo of the UI in its current state

![demo](https://user-images.githubusercontent.com/1094740/27771205-057c4e00-5f42-11e7-8d67-8aa96b310d2b.gif)

As you can see, not all selections actually trigger the Ajax request, in our situation some parts have "variations" which cannot be retrieved and must be done on live at run time (3rd party system requirement)

I admit that if there was not a client/design constraint against having the UI look as it does, then again your suggestion of just having it as a search would also be very suitable!

I think a simple validation that is not async would be more than suitable, along with a little documentation on "if you need to do X" that would probably help most users looking for this.
