### ISSUE TITLE
Box closes automatically when a radio is clicked, in slot beforeList.

### ISSUE THREAD

**Issue by adrianoresende** [shentao/vue-multiselect#416]
Code live: https://codepen.io/zullcore/pen/qjKbqx
My work:
![image](https://user-images.githubusercontent.com/798755/27839414-6947b88a-60c7-11e7-99eb-95bdec66ab4f.png)

Expected: The radio filters the list, and the box must be closed when the list is selected and not on the radio.

Problem: In the `beforeList` slot, the box closes automatically when a radio is clicked.

**Comment by shentao** [comment]
Just a guess: 
Have you tried adding `@mousedown.stop` or `@click.stop` modifiers to the slot content? That might be enough to prevent multiselect from catching the event and closing.

**Comment by adrianoresende** [comment]
I had tested on `.prevent` and` .stop`, none of them work =(
You codepen worked? but for me, not worked.

**Comment by phcoliveira** [comment]
I would like to put a filter input inside `beforeList`, but even when using `@click.stop` I cannot have the input focused.

**Comment by Jung-Younghun** [comment]
I got same issue. 
I add checkbox to select all items in beforeList slot. but list box is closed automatically when checkbox is clicked.
but I resolve this issue by using dummy layer with css(like hack).

_slot template
```
 <li class="multiselect_element check-all" slot="beforeList">
    <div class="common-dropdown-checkbox-item">
       <div class="option__desc">
            <span class="option__text">
                  <input type="checkbox" id="test" v-model="$data._isSelectAll"/>
                  <label for="test" @focus.prevent class="label-check-all">Select All</label>
            </span>
    </div>
    <div class="check-all-layer" v-on:click="_setStateAllCheckbox()" @click.stop></div>
</li>
```
_some css
```
.multiselect .multiselect_element.check-all .common-dropdown-checkbox-item{
	position: relative;
        ...
}
.multiselect .multiselect_element.check-all .check-all-layer{
	position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
}
```

This issue is come from closing list box by clicking checkbox or radio in beforeList slot.
So, I attach click event to selecting all items on dummy layer(.check-all-layer).
Controlling CSS of this layer, it overwrap DOM(checkbox element or radio element).
This way is prevent to close list box automatically but is not right way.
