### ISSUE TITLE
Icons? :)

### ISSUE THREAD

**Issue by iamvitali** [shentao/vue-multiselect#485]
Is it possible to include icons in the select option label?

As an example, a FA icon: `<span class="fa fa-line-chart" aria-hidden="true"></span>`.

I've tried simply putting that HTML into the label but it displayed it as is. :sweat_smile:

**Comment by shentao** [comment]
This is possible for multiple elements (tags) but not yet possible for single selects (because the value’s label is displayed as the text value of the `<input>`.
I will consider having a slot for the value when in single-select mode and always using it instead of replacing the value of the `<input>` element when `searchable` equals `true`.

**Comment by derekphilipau** [comment]
This is what I've been doing for fa-icons:
```
      <multiselect v-model="value" placeholder="" label="title" track-by="title" :options="options" :option-height="104" :show-labels="true">
        <template slot="option" slot-scope="props">
          <div class="option__desc"><span class="option__title"><i class="fa" v-bind:class="'fa-' + props.option.icon"></i> {{ props.option.title }}</span></div>
        </template>
      </multiselect>
```
Options array:
```
        value: { title: 'Github', icon: 'github' },
        options: [
          { title: 'Github', icon: 'github' },
          { title: 'Google', icon: 'google' },
          { title: 'Facebook', icon: 'facebook' },
          { title: 'Reddit', icon: 'reddit' }
        ]
```
