### ISSUE TITLE
[featurerequest] handle click on optiongroup 

### ISSUE THREAD

**Issue by someother1** [shentao/vue-multiselect#517]
Hi

In first place - thanks for this awesome component!

We would like to select / unselect all options of one optiongroup, if the optiongroup is clicked.
It would be nice, if an optiongroup click could be custom handleable, so that everyone could trigger his own method `@optiongroupclick` or smiliar.

kindly regards

**Comment by branquito** [comment]
Any changes on this one, this would be really useful. Thanks.

**Comment by masix** [comment]
You can do it using "Custom option template"

**Comment by shentao** [comment]
This sounds like a reasonable idea. Will consider implementing it unless someone does it before me (PR welcome).

**Comment by pepf** [comment]
While searching for this functionality I also came across PR #360 , which seems to implement more or less what is described above. 
Is there a reason why this hasn't hasn't been continued?

**Comment by shentao** [comment]
I feel really guilty right now – it might have not been merged because I didn’t found the time to properly investigate the PR... Anyway, this feature request and the PR you mentioned talk about slightly different functionalities, altough those could be merged. I plan on doing some work on Multiselect this weekend so I might finally merge it as well as add the event for group label clicks.

**Comment by shentao** [comment]
The PR has been merged! :) Though you can’t directly listen to `@option-group-label` event, the option group selecting is working in the newest release. :)
