### ISSUE TITLE
Feature: Add customSearch option

### ISSUE THREAD

**Issue by Fohlen** [shentao/vue-multiselect#530]
It would be nicely to have a `customSearch` function parameter.
I know that this is hackily-possible using `internalSearch=false` and `@search-change`, however this does have some disadvantages

- the current approach will require to expand/lessen the list of available options
- this approach gradually decreases performance, since every change might trigger changes to the `vue-watch` cycle

In some cases, say I have a complex object with a hidden value I want to search for (smart search), an API such as:

```
customSearch(searchQuery) => {
return this.currentlySelectAble.filter((somefilterlambdawithcomplexdata))
```

Would be amazing.
An example of such a complex data is, let's say, I have an `id` that is usually shown via the `label`, but I also want to search for it using `#` prefix.

**Comment by shentao** [comment]
There shouldn’t be any gradual decrease in performance when using `internalSearch="false"`. The number of watch related operations stays the same.
Actually, you can even improve the performance if you debounce the filtering. Additionally, the external search could be slightly faster because it might not require all the checks that are happening in the current search function.

That the current approach is much more extendable and allows for asynchronous code, which I believe is superior than the proposed one. 

Additionally, such `customSearch` function would have to accept multiple arguments to match the requirements (thus requiring the user to know the internal API).

Although I’m rather against this addition let’s wait a few days and if there are other opinions.  :)
