### ISSUE TITLE
Placeholder and form values over multiselect content?

### ISSUE THREAD

**Issue by PrimozRome** [shentao/vue-multiselect#596]
I have one issue, probably CSS related but just can't figure it out.

Have some `vue-multiselect` CSS overrides but have the same behaviour if I remove them.

![screen shot 2017-11-28 at 15 29 42](https://user-images.githubusercontent.com/1180467/33324861-1515117e-d451-11e7-9eef-c18233af247f.png)

Been spinning my head over few days to solve this but without success. Any ideas?

**Comment by PrimozRome** [comment]
I have figured out one thing. If I remove `display: none;` from `multiselect__content-wrapper` manually from Chrome dev tools, then it is displayed correctly. 

![screen shot 2017-11-28 at 17 52 55](https://user-images.githubusercontent.com/1180467/33332671-29730342-d465-11e7-868d-60cd10bfb048.png)

If I use the dropdown button to activate options then I get result as seen above.

**Comment by PrimozRome** [comment]
I have figured out... 

`.multiselect__content-wrapper`and `.multiselect__active` must have the same z-index, otherwise you get above result.

**Comment by shentao** [comment]
It seems there’s a problem with the `z-index` property. Please make sure the component where vue-multiselect is located has higher `z-index` value than other components/elements. Also keep in mind that things like `position: relative` affect the `z-index` property.

**Comment by davidjr82** [comment]
I had a very similar issue (in my case, when I had a prettycheckbox under the select-wrapper).

The problem was that this css is not being applied: `.multiselect--active { z-index: 50 }` so I write this important css inside my component  `.multiselect--active { z-index: 50!important; }` and now is working fine. 

I guess this is the same issue that @PrimozRome had explained. Hope it helps.
