### ISSUE TITLE
HELP: preselect option object based on string value

### ISSUE THREAD

**Issue by PrimozRome** [shentao/vue-multiselect#600]
Hi,

I am building my `vue-multiselect` country list based on API call. I feed multi-select options to the component where each option is an object like `{ id: 'US', name: 'United States' }`. 

Now I want to pre-select a value in this select component. 

If I feed in `:value="{ id: 'US', name: 'United States' }"` then it preselects option correctly.

If I feed in only `:value="'US'"` then it won't preselect. 

Is it possible to somehow preselect based on this string only value and tell `vue-multiselect` to match it to the `id` attribute of an option object?

**Comment by shentao** [comment]
This is an already long existing problem.
It could be done so that you can preselect an element based on a specified key.
However, this will fail once we do async options, because then there’s no warranty that the options will be present in the options list. Thus, for example, you won’t be able to show the country name if you only have the `id`. I also don’t like the idea, because when you select some options, you only get a key instead of the whole object. This might introduce problems you haven’t thought right now.

This might be an opt-in option in the 3.0 release though.

As for now, I would do a `find` on the list of countries to pass. You can also construct a computed property to do it for you.

**Comment by PrimozRome** [comment]
thanks @shentao ... I did a workaround, so that I always pass just array of ID's to you component... Then in the formatLabel I call my own method which finds object by vue-multiselct-value and display right option label.
