### ISSUE TITLE
Unexpected behavior with Vuex

### ISSUE THREAD

**Issue by saintplay** [shentao/vue-multiselect#602]
Please check the sandbox https://codesandbox.io/s/030wm2806n

 I got `undefined  undefined` instead of *select option*, and in my application I actually get an error `"TypeError: Cannot read property 'id' of null"` ( I tried, but I couldn't reproduce it)

So, I assume vuex is wrapping my objects with observables, and that is the problem

**Comment by shentao** [comment]
Hey! I think you got some things wrong.
1) The fullName function should handle the case where the `name` and `fullName` don’t exist. Otherwise, you will get `undefined undefined` because inside `${name} ${fullName}` both of those values are undefined given `data` is null. Thus trying to get `name` from `null` is not an existing value.

2) If you use Vue-Multiselect for selecting objects you have to make sure that the preselected value has the same structure as the options you pass. Because it will pass the whole selected option into the mutation.

See the fixed version below and compare it with your code. Cheers!

https://codesandbox.io/s/4x7v2v53jw
