### ISSUE TITLE
CSS Not working 

### ISSUE THREAD

**Issue by nusendra** [shentao/vue-multiselect#620]
![screenshot from 2018-01-02 09-34-12](https://user-images.githubusercontent.com/8466308/34473031-2c62a160-efa0-11e7-9d65-521d7da7ea72.png)

If i remove the css, this works perfectly (without style)

![screenshot from 2018-01-02 09-35-39](https://user-images.githubusercontent.com/8466308/34473039-528055f4-efa0-11e7-86c9-70b4ac25b60c.png)

how to fix this? Thanks

**Comment by shentao** [comment]
Please remember to add `<style src="vue-multiselect/dist/vue-multiselect.min.css"></style>` to your code/component.

**Comment by nusendra** [comment]
i already add that css. the result is first image. If i remove that css, the result is the second image

**Comment by shentao** [comment]
And that is the correct behaviour. You need the CSS added somewhere in your code.

**Comment by ByScripts** [comment]
I know this issue is old, but I don't understand something and I like to understand ^^

This package exports a Vue Single File Component.

In this Vue component, there is a `template`, a `script` and a `style` tag.

And therefore, I don't understand why the style is not applied and why we need to import the dist CSS.

Thank you :)
