### ISSUE TITLE
Options value refreshed for each <vue-multiselect> when changing one of them

### ISSUE THREAD

**Issue by devondahon** [shentao/vue-multiselect#665]
When having more than one `<vue-multiselect>` in the same component, you can see that the `options` value of all `<vue-multiselect>` is refreshed when changing only one of them. How to prevent this behavior ? 

https://jsfiddle.net/maxagaz/hcr3sco5/

I noticed the same issue with [`<vue-select>`](https://github.com/sagalbot/vue-select/issues).

**Comment by shentao** [comment]
I imagine this is just Vue rerendering the page. Use an array in your data/computed property/getters instead of methods that return values, otherwise those probably can’t be tracked (and thus lead to avoiding a complete rerender). A hint for this is that it always calls the `optionsA` and `optionsB` in the same order.
