### ISSUE TITLE
Consider switching the no results message to use v-if

### ISSUE THREAD

**Issue by ztolley** [shentao/vue-multiselect#666]
When the component renders it renders the message telling the user there are no results with `v-show`, this means the markup is always there, this can be confusing for users of screen readers.

Consider using v-if instead, so the markup is only in the DOM when there are really no suggestions found, and also make the message something that can be overridden. 

I'm more than happy to do it and submit it as a PR.

**Comment by shentao** [comment]
Hey! `v-if` caused some issues back in the days but I think this shouldn’t be a problem anymore. I was experimenting with it just yesterday and haven’t seen any regressions.

Feel free to make a PR! :)

**Comment by plweil** [comment]
I'm not sure what that really gets you. display:none (which is what v-show toggles, I think) hides content from *all* users, including screenreader users. If you do need to add something to the DOM, then you'll need to alert screenreader users with an ARIA live region -- that's something you might want to minimize. Regarding other content, if you use aria attributes that refer to other elements (e.g., aria-controls, aria-labelledby, aria-describedby, etc.), you're better off showing and hiding those elements with v-show. Otherwise the code will be invalid and the aria will be useless.
