### ISSUE TITLE
Objects Options, but string value

### ISSUE THREAD

**Issue by bernhardh** [shentao/vue-multiselect#682]
I use vue-multiselect inside a custom component, with an array of objects as options, but the value is just a string. I tried to follow the documentation, but can't find a solution for the problem.

Please see https://jsfiddle.net/91ztus9n/3/

There is the parent component "App" which has just 2 elements:
- The "Child" component `<my-component>`, which is just a wrapper for vue-multiselect
- A `<pre>` tag showing the value.

As you can see, the value of the parent component "App" is "medium" in the beginning. The first problem is, that the selectbox hasn't selected the right option. If you click on the selectbox and select one option (for example "Large Size"), the parent component is updated as expected and the value is set to "large", but the selectbox now says once again "Select option" instead showing "Large Size".

Can you give me a helping hand? What am I doing wrong?

**Comment by shentao** [comment]
Hey!

This is because Vue-Multiselect is accepts and returns whole objects for Object arrays. This means that if you want to preselect a value, you have to pass the object to Multiselect. There are reasons why it is working this way – most notably the support of dynamic asynchronous options where you wouldn’t be able to show the selected label if it wasn’t already present in the options list (to look up by `id`).

Of course you can always build a wrapper component like you did, so that you can operate just on the `id` property instead of passing the whole object.

I made some adjustments to your code that make it work like you described: https://jsfiddle.net/shentao/yo767npo/

**Comment by bernhardh** [comment]
Thank you very much for your help. I wasn't sure if this behavior was a "bug or a feature" ;)

**Comment by shentao** [comment]
Trust me I got this feeling quite often regarding this library and the extensive API... Hopefully 3.0 will make it much smaller and flexible enough for all those fancy features to be implemented on the user side.
