### ISSUE TITLE
Cursor keys support (up and down arrow)

### ISSUE THREAD

**Issue by chavlji** [shentao/vue-multiselect#758]
Normal html select allows user to walk-through options using up/down keyboard keys when select has focus and it is in closed state. Multiselect seems to ignore that.

It's very useful in some cases, when you want to immediate affect for previewing each object.

**Comment by shentao** [comment]
This is already implemented in v3.

**Comment by codezomb** [comment]
> This is already implemented in v3.

@shentao any reason why this couldn't be back ported to v2? Upgrading to a major release version for folks usually isn't straight forward, and requires significant testing. v2 being the current release, is essentially broken for long lists.

**Comment by shentao** [comment]
The current version is strongly coupled to the focus state for its behaviour since in v2 focus = open dropdown. What I meant by my previous comment is that the v3 version should make it pretty easy to add this behaviour even if it’s not there by default. That is because in v3 having focus on the multiselect doesn’t necessarily mean it’s open (you got to press space, arrow or enter to open).
