### ISSUE TITLE
Change the search mechanism

### ISSUE THREAD

**Issue by TomFranssen** [shentao/vue-multiselect#788]
I have a list of countries in my dropdown. One of the countries name is Réunion. I would like that country to show up in the results when I start typing Re (without the é). Is it possible to change the way the search is being done? Now it only comes up when I type in Ré.

Check out this JSFiddle for an example:
https://jsfiddle.net/gn8byd6o/

Thanks!

**Comment by havgry** [comment]
Issues is not really for support :)

You could use the `search-change` event like so: [https://jsfiddle.net/fb6rws21/](https://jsfiddle.net/fb6rws21/). Obviously, you'd have to sanitize the option labels yourself (or perhaps use [diacritics](https://github.com/andrewrk/node-diacritics#readme)), and my example doesn't take into account that the query can contain diacritics but you get the idea.

**Comment by shentao** [comment]
Thanks @havgry!

The best way to approach is by providing your own search implementation so that it fits your needs. That can be done similar to how the async example looks like in docs: https://vue-multiselect.js.org/#sub-asynchronous-select where you manage the `options` list yourself. This way you can also search in multiple fields rather than just based on the label.

**Comment by TomFranssen** [comment]
Thanks everybody, I'll look into it.
