### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by andreasvirkus** [shentao/vue-multiselect#836]
@shentao Just wondering if this repo's still actively maintained?
Would you be willing to consider other maintainers alongside you? There's plenty of issues
stacking up (most with quick/easy fixes) and some open PRs that haven't got the attention they deserve.

Edit: Sorry, just read your comment from 25 days ago which states you're working on v3 as well.
Did not mean for the original post to sound hostile in any way.

Best regards,
andreas

**Comment by shentao** [comment]
Hey! No worries – no offence taken. I also understand how frustrating it is and trust me – it’s the same on my end. I would like to deliver the best experience possible. And I’m very sorry for not being able to hold on to that for a long time now. Hopefully, this will change soon.

I hoped to release v3 sooner but turns out the rewrite takes much more time than I hoped it will. The conclusion is we will need to release at least one more release for 2.x to patch the current issues before fullying committing to v3.

The issue with quick/easy fixes is that half the time they only look simple and turn out to break some edge cases. Especially true with the keyboard navigation. 

Enough of the excuses though. Will try to prepare a release today/tomorrow once we (me and @p-adams) done with testing the master and fixing the problems we find.

**Comment by shentao** [comment]
Released v2.1.2 😅
