### ISSUE TITLE
[Feature Request] Debug mode to allow you to inspect and style elements

### ISSUE THREAD

**Issue by erikaskm** [shentao/vue-multiselect#957]
It's difficult to style this component. It would be good to have a debug mode where you can click out of it without closing it, so that you can inspect the DOM elements.

**Comment by Turajek** [comment]
Yeah, It's really hard to style this component. @shentao, please think about some style documentation. Inspecting every single element in devtools and consider what each element do really sucks.

**Comment by shentao** [comment]
That is so true! Imagine having to maintain a library like that... Can’t fix this now with the current version, but just to let you know – the v3 is built in a slightly different way (the way it manages focus), so that you should be able to debug the styles much more easily, since it won’t be closing when you operate in the devtools.
